actions: [
          "binds to",
          "which binds to",
          "Caproate binds to",
          "co-treated with",
          "inhibits the reaction",
          "promotes the reaction",
          "catalyzed by",
          "results in increased phosphorylation of",
          "results in decreased phosphorylation of",
          "affects the phosphorylation of",
          "results in increased methylation of",
          "results in decreased methylation of",
          "affects the methylation of",
          "results in increased acetylation of",
          "results in decreased acetylation of",
          "affects the acetylation of",
          "results in increased cleavage of",
          "results in decreased cleavage of",
          "affects the cleavage of",
          "results in increased sumoylation of",
          "results in decreased sumoylation of",
          "affects the sumoylation of",
          "results in increased ubiquitination of",
          "results in decreased ubiquitination of",
          "affects the ubiquitination of",
          "results in increased expression of",
          "results in decreased expression of",
          "affects the expression of",
          "results in increased abundance of",
          "results in decreased abundance of",
          "affects the abundance of",
          "results in increased stability of",
          "results in decreased stability of",
          "affects the stability of",
          "results in increased localization of",
          "results in decreased localization of",
          "affects the localization of",
          "results in increased activity of",
          "results in decreased activity of",
          "affects the activity of",
          "results in increased metabolism of",
          "results in decreased metabolism of",
          "affects the metabolism of",
          "results in increased oxidation of",
          "results in decreased oxidation of",
          "affects the oxidation of",
          "results in increased reduction of",
          "results in decreased reduction of",
          "affects the reduction of",
          "results in increased hydrolysis of",
          "results in decreased hydrolysis of",
          "affects the hydrolysis of ",
          "results in increased glucuronidation of",
          "results in decreased glucuronidation of",
          "affects the glucuronidation of",
          "results in increased glycosylation of",
          "results in decreased glycosylation of",
          "affects the glycosylation of",
          "results in increased farnesylation of",
          "results in decreased farnesylation of",
          "affects the farnesylation of",
          "results in increased lipidation of",
          "results in decreased lipidation of",
          "affects the lipidation of",
          "results in increased sulfation of",
          "results in decreased sulfation of",
          "affects the sulfation of",
          "results in increased hydroxylation of",
          "results in decreased hydroxylation of",
          "affects the hydroxylation of",
          "results in increased carboxylation of",
          "results in decreased carboxylation of",
          "affects the carboxylation of",
          "results in increased glutathionylation of",
          "results in decreased glutathionylation of",
          "affects the glutathionylation of",
          "results in increased glycation of",
          "results in decreased glycation of",
          "affects the glycation of",
          "results in increased alkylation of",
          "results in decreased alkylation of",
          "affects the alkylation of",
          "results in increased degradation of",
          "results in decreased degradation of",
          "affects the degradation of",
          "results in increased folding of",
          "results in decreased folding of",
          "affects the folding of",
          "results in increased susceptibility to",
          "results in decreased susceptibility to",
          "affects the susceptibility to",
          "results in increased chemical synthesis of",
          "results in decreased chemical synthesis of",
          "affects the chemical synthesis of",
          "results in increased secretion of",
          "results in decreased secretion of",
          "affects the secretion of",
          "results in increased uptake of",
          "results in decreased uptake of",
          "affects the uptake of",
          "results in increased transport of",
          "results in decreased transport of",
          "affects the transport of",
          "results in increased import of",
          "results in decreased import of",
          "affects the import of",
          "results in increased export of",
          "results in decreased export of",
          "affects the export of",
          "results in increased splicing of",
          "results in decreased splicing of",
          "affects the splicing of",
          "results in increased mutagenesis of",
          "results in decreased mutagenesis of",
          "affects the mutagenesis of"
]